### PR TITLE
Trigger Cloudflare Pages deployment

### PR DESCRIPTION
**Pull request by siketyan**
Related: #182 

Currently, some of the blog articles are missing on https://canary.approvers.dev/ .
This is because the build command configuration was invalid and site-data was not patched.
So I fixed the command on Cloudflare Pages, but it is needed to trigger a deploy on the production branch (main).

This PR is exactly empty, but triggers a deployment on merged.

### CODE REVIEW

**Review by loxygenK — APPROVED** [review]
Null を、Approve します！

**Review by soshiharami — APPROVED** [review]

**Review by laminne — APPROVED** [review]
_Approve_

**Review by Nanai10a — APPROVED** [review]
approve to null

**Comment by siketyan** [comment]
Confirmed the articles are appeared on the preview (https://c5bd556e.approvers.pages.dev/blog).
So I will merge this PR.

**Pull request merged**
